[package]
name = "xyz"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
futures = "0.3.23"
log = { version = "0.4.17", default-features = false }
tokio = { version = "1.20.1", features = ["full"] }
